language: cpp
compiler:
  - clang
notifications:
  email: spencer.f.russell@gmail.com
env:
    - JULIAVERSION="julianightlies"
    - JULIAVERSION="juliareleases"
before_install:
  - sudo add-apt-repository ppa:staticfloat/julia-deps -y
  - sudo add-apt-repository ppa:staticfloat/$JULIAVERSION -y
  - sudo apt-get update -qq -y
  - sudo apt-get install libpcre3-dev julia -y
script:
  - julia -e 'Pkg.init()'
  - julia -e 'Pkg.add("BinDeps"); Pkg.checkout("BinDeps")' # latest master needed for Pacman support
  - julia -e 'Pkg.clone(pwd()); Pkg.build("AudioIO")'
  - julia -e 'Pkg.test("AudioIO", coverage=true)'
after_success:
- if [ $JULIAVERSION = "juliareleases" ]; then julia -e 'cd(Pkg.dir("AudioIO")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
